/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lcj_ndk_demo_3_NativeJniAdder */

#ifndef _Included_com_lcj_ndk_demo_3_NativeJniAdder
#define _Included_com_lcj_ndk_demo_3_NativeJniAdder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lcj_ndk_demo_3_NativeJniAdder
 * Method:    newObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_lcj_ndk_1demo_13_NativeJniAdder_newObject
  (JNIEnv *, jclass);

/*
 * Class:     com_lcj_ndk_demo_3_NativeJniAdder
 * Method:    execute
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_lcj_ndk_1demo_13_NativeJniAdder_execute
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
