/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lcj_ndk_demo_1_HelloNDK */

#ifndef _Included_com_lcj_ndk_demo_1_HelloNDK
#define _Included_com_lcj_ndk_demo_1_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lcj_ndk_demo_1_HelloNDK
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lcj_ndk_1demo_11_HelloNDK_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
